language: node_js
node_js:
  - "7"

before_script:
  - npm install -g gulp
  - npm install gulp --save
  - npm install gulp-cli --save-dev
  - npm install gulp-sass --save-dev
  - npm install gulp-uglify --save-dev
 
script: gulp

env:
  global:
    - secure: "gXrt8tC1IBDv9KBUAGOCWrPyoHdtFrOVtZc+vshFcA7vGUdFwpULDuSPJm3Ysvcwtv/bS1e9knhMN2fnnsN/5J/v2EgB4026Zo4/AiXyf2fM4DkgTCq4AH43lP9CyPWKLI3JAN8BHJXLvtYC5FXi3MXiNNVZVYTYf+zaWY3DnNGt791d1j2+WQsywVCazegaTh7x5UA0v/k/UmGQL+tz3PCkyv7Z5lf5Wuy8A+b9pmFNyrMb6tzkZcFdZ0EoIcI4ts9mIayy4vu/uCOnZcR5LL1uVCIhCNOHewxa9/xUdrvJX60KREKyWi0VGhKGgZZZErBcIJuYbvx2iI1PTlyoy7+fjIKJGSwSYkTU/s8GLyhUafnWNyXLEHtWbgmkT5nVxh47sWnJU2ix7jcOOuZmtSAJ8nn1bg8cq3w4srXE4B+aXboNcv+nD2usRw0jRRcrcEwMFAOE3alsRmtT8gxplJ4Dvex37IT0qMbfobxYFx94oX2ZfpzrFshtc/b67LHPFcLHzzIKuipa7GJCL8HTzipSyYA8fo2oQL7cOji4A4zb75MRCNLjB0vd27wSY3X7dwP3ygc30cDJO+ADTXio5cjYmvrPQCyZa3Pls0esHRg7SQMpSbgvpWFa+vADmaF/bvowPjXGf6zXErLybbeBQN3jr+qYq+/uHmFjs4xQCBE="


after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='release-master' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=maruuusa83/profile /tmp/travis-automerge"

